### ISSUE TITLE
improvements with multi-threading

### ISSUE THREAD

**Issue by kaczmarj** [johnjmurray/harlem-air-quality#3]
after conversations with the benevolent owner of this repository, we realized we can use a queue and multiple threads to make this script more efficient. one thread can be dedicated to receiving data from the raspberry pi, another thread for writing that data to disk, and a third thread to push the csv to github. each of these threads should probably subclass the `threading.Thread` class.

here is our todo (feel free to edit)

- [ ] use one of the queues in the `queue` module (ie `queue.Queue` or `queue.SimpleQueue`) or `collections.deque`.
- [ ] implement producer thread. this thread will record data from the raspberry pi infinitely. the data will be put into the queue in order. each sample should probably be a namedtuple. there is an option to not block when adding to the queue. should we use that? we probably don't need to block.
- [ ] implement consumer thread. this thread will write whatever is in the queue to a spreadsheet. also happens in an infinite loop.
- [ ] refactor the commiter and pusher function to be a subclass of `threading.Thread`.

questions:

1. which queue object should we use? `queue.Queue` or `queue.SimpleQueue` or `collections.deque`? the last one seems to be much more efficient than the `queue` objects. and because we only have a single producer (one thing writing to the queue), perhaps `collections.deque` is ok?
2. how often should the consumer thread write to disk? whenever the queue is not empty? or every N seconds? perhaps we can write whenever the queue is not empty, because it will be updated every N seconds by the producer thread, so we won't be constantly writing to disk.
3. what should the buffer size of the queue be? does it even matter for our purposes?

**Comment by kaczmarj** [comment]
here are links to relevant documentation

- [`threading.Thread` object](https://docs.python.org/3/library/threading.html#thread-objects)
- [`queue` module](https://docs.python.org/3/library/queue.html)

and some pseudo code for how the producer and consumer might behave

```python
# producer
while True:
  sample = getSample()
  queue.put(sample, block=False)

# consumer
while True:
  if not queue.empty():
    sample = queue.get()
    writeToFile(sample)
```

and here's an example of subclassing a thread

```python
import threading
import time
import RPi.GPIO as GPIO

class Producer(threading.Thread):
    def run(self):
        while True:
            sample = (time.time(), GPIO.input(DUSTPIN_INPUT))
            queue.put(sample)

Producer(daemon=True).start()
```

**Comment by kaczmarj** [comment]
here's where we left off on the consumer side...

we can't figure out how to keep epochs to exactly 30 seconds. though we are slowly coming to the conclusion that sticking to 30 seconds does not matter much.

```python
import itertools
import time
import random
import queue

# Synthesize data.
q = queue.Queue()
for timestamp in itertools.count(0, step=1):
    q.put((timestamp, random.randint(0, 1)))
    if timestamp > 185:
        break

startOfEpoch = True
epochDuration = 0

while True:
    timestamp, value = q.get(block=False)  # block=False for debugging only
    if startOfEpoch:
        t0 = timestamp
        startOfEpoch = False
        pulseDuration = 0

    if value == 0:
        pulseStart = timestamp
        isLow = True
        while isLow:
            pulseStop, value = q.get(block=False)
            if value != 0:
                isLow = False
        pulseDuration += pulseStop - pulseStart
        
    epochDuration = timestamp - t0
    if epochDuration > 30:
        startOfEpoch = True
        print(f"{pulseDuration}\t{epochDuration}")
```

**Comment by johnjmurray** [comment]
@kaczmarj ,

Pls review the proposed changes in the linked pull request. I added your proposed code to the ConsumerThread class and removed the Sample class and getOneSample functions, since they are no longer in use.

**Comment by johnjmurray** [comment]
I uh...got excited. Open a new issue if you wish.
